openapi: 3.0.0
info:
  version: 1.0.0
  title: Auth API
  description: "StudyGen"
servers:
  - url: /
paths:
  /:
    get:
      responses:
        '200':
           description: Registration page
  /home:
    get:
      responses:
        '200':
           description: Registration page
  /register:
    get:
      summary: Get registration page
      description: Returns the registration page
      responses:
        '200':
          description: Registration page
    post:
      summary: Register a new user
      description: Registers a new user with the provided details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - loginId
                - name
                - email
                - password
                - confirmPassword
              properties:
                loginId:
                  type: string
                  default: 'example'
                name:
                  type: string
                  default: 'example'
                email:
                  type: string
                  format: email
                  default: 'example@gmail.com'
                password:
                  type: string
                  default: '123'
                confirmPassword:
                  type: string
                  default: '123'

      responses:
        '200':
          description: User registered successfully
        '400':
          description: Invalid input
  /login:
    get:
      summary: Get login page
      description: Returns the login page
      responses:
        '200':
          description: Login page
    post:
      summary: Log in a user
      description: Logs in a user with the provided credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - loginId
                - password
              properties:
                loginId:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Unauthorized
  /logout:
    get:
      summary: Log out a user
      description: Logs out the currently logged-in user
      responses:
        '200':
          description: User logged out successfully
  /resetPassword:
    post:
      summary: Reset user password
      description: Resets the password for the specified user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - newPassword
              properties:
                email:
                  type: string
                  format: email
                newPassword:
                  type: string
      responses:
        '200':
          description: Password reset successfully
        '400':
          description: Invalid input

